name: Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Enforce Structure
        run: |
          echo "Event name: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            python .github/workflows/enforce_problem_structure.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.event.pull_request.number }} pull_request
          else
            python .github/workflows/enforce_problem_structure.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.sha }} push
          fi
